# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T04:15:36+00:00



import argparse
import json
import os
from datetime import datetime
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity, HTTPBearer
from fastapi import Path, Query, Request
from pydantic import AnyUrl, conint, constr

from models import (
    AnalysesAnalysisIdAlertsGetResponse,
    Analysis,
    CodereviewsReviewIdGetResponse,
    Health,
    IssuesProjectIdAlertKeyGetResponse,
    Language,
    Language1,
    Metric,
    MetricsList,
    Mode,
    OpenapiGetResponse,
    Operation,
    ProjectDetails,
    ProjectId,
    ProjectList,
    ProjectsProjectIdSettingsAnalysisConfigurationGetResponse,
    ProjectsProjectIdSettingsAnalysisConfigurationPutResponse,
    Queryjob,
    QueryjobProjectResults,
    QueryjobResultsOverview,
    Source,
    UploadSession,
    Version,
    WorkerLabel,
)

app = MCPProxy(
    description="The REST API for LGTM provides data so that you can customize how you integrate LGTM analysis into your workflow. It includes the following resources:\n  * `/` ([API root](https://lgtm.com/help/lgtm/api/api-v1#LGTM-API-specification-API-root))&mdash;get version information or download the specification in OpenAPI format.\n  * `/projects` ([Projects](https://lgtm.com/help/lgtm/api/api-v1#LGTM-API-specification-Projects))&mdash;list projects, get a summary of the current status for a project, or add new projects.\n  * `/analyses` ([Analyses](https://lgtm.com/help/lgtm/api/api-v1#LGTM-API-specification-Analyses))&mdash;get a summary of results, download all the alerts, or trigger analysis for a specific commit.\n  * `/codereviews` ([Code reviews](https://lgtm.com/help/lgtm/api/api-v1#LGTM-API-specification-Code-reviews))&mdash;trigger code review for a patch, and view the results.\n  * `/operations` ([Operations](https://lgtm.com/help/lgtm/api/api-v1#LGTM-API-specification-Operations))&mdash;get information about long-running tasks, for example, analyses or code reviews that you've requested.\n  * `/snapshots` ([Snapshots](https://lgtm.com/help/lgtm/api/api-v1#LGTM-API-specification-Snapshots))&mdash;download and upload databases representing a snapshot of a codebase.\n  * `/queryjobs` ([Query jobs](https://lgtm.com/help/lgtm/api/api-v1#LGTM-API-specification-Query-jobs))&mdash;submit queries to evaluate against existing projects, and download their results.\n  * `/system` ([System](https://lgtm.com/help/lgtm/api/api-v1#LGTM-API-specification-System))&mdash;get information on the health or usage of the system.\n\nFor an overview and getting started topics, see [API for LGTM](https://lgtm.com/help/lgtm/api/api-for-lgtm).\n",
    title='LGTM API specification',
    version='v1.0',
    servers=[{'url': 'https://lgtm.com/api/v1.0'}],
)


@app.get(
    '/#-datamodel-code-generator-#-root-#-special-#',
    description=""" Get the version information of this API. """,
    tags=['version_info'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_version():
    """
    Version information
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/analyses/{analysis-id}',
    description=""" Get a summary of the analysis results for a specific analysis identifier.

To find the analysis identifier for a commit, use the `/analyses/{project-id}/commits/{commit-id}` endpoint. For more information, see [Get analysis summary for a specific commit](https://lgtm.com/help/lgtm/api/api-v1#opIdgetAnalysisForCommit).

This endpoint reports the commit analyzed and a summary of the results for each language. Alternatively, you can use this identifier to download full details  of all the alerts found by the analysis. For more information, see [Get detailed alert information](https://lgtm.com/help/lgtm/api/api-v1#opIdgetAlerts).
 """,
    tags=['code_analysis'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_analysis(
    analysis_id: constr(pattern=r'[a-f0-9]+', min_length=40, max_length=40) = Path(
        ..., alias='analysis-id'
    )
):
    """
    Get analysis summary
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/analyses/{analysis-id}/alerts',
    description=""" Download all the alerts found by an analysis.
Use the `Accept:` request header to specify the output media type as either CSV or [SARIF](https://lgtm.com/help/lgtm/sarif-results-file): 

- `application/sarif+json`: Alerts in SARIF format. If no version is specified the latest supported SARIF version is used.
- `application/json`: Alerts in SARIF format (*deprecated*). 
  If no version is specified, [SARIF 2.0.0](http://docs.oasis-open.org/sarif/sarif/v2.0/sarif-v2.0.html) 
  is used for backwards compatibility.

- `text/csv`: Alerts in CSV format. The `text/csv` media type has two optional parameters:
   - `charset`: determines the character encoding of the text, by default UTF-8.
   - `header`: determines whether a header row with column names is `present` or `absent`.
      The default value for this parameter is `present`.
      For example, an Accept header with value `text/csv; header=absent` 
      would result in CSV output without a header row.
    



To find the analysis identifier for a commit, use the `/analyses/{project-id}/commits/{commit-id}`  endpoint. For more information, see [Get analysis summary for a specific commit](https://lgtm.com/help/lgtm/api/api-v1#opIdgetAnalysisForCommit). 
 """,
    tags=['code_analysis', 'version_info'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_alerts(
    analysis_id: str = Path(..., alias='analysis-id'),
    sarif_version: Optional[str] = Query(None, alias='sarif-version'),
    excluded_files: Optional[bool] = Query(False, alias='excluded-files'),
):
    """
    Get detailed alert information
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/analyses/{project-id}',
    description=""" Trigger the analysis of a specific commit to a project. If a previous attempt to analyze that commit failed, this triggers a fresh analysis.  This is supported for all LGTM projects, regardless of repository type or host. The commit must be available in the main repository, but can be on a branch that isn't tracked by LGTM. For both LGTM.com and LGTM Enterprise, you must include an access token with the `analyses:write` scope.

When you request the analysis of a commit, the API returns:
- `operation-id`: used to track the status of the task using the `/operations` endpoint. For more information, see [Get operation status](https://lgtm.com/help/lgtm/api/api-v1#opIdgetOperation).
- `status`: initially pending.
- `task-result`: containing information about the progress and results of the analysis.
 """,
    tags=['code_analysis'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def request_analysis(
    project_id: int = Path(..., alias='project-id'),
    commit: str = ...,
    language: Optional[Language] = None,
):
    """
    Run analysis of a specific commit
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/analyses/{project-id}/commits/{commit-id}',
    description=""" Get a summary of the analysis results for a specific commit, or the latest commit, to a project. (For projects configured for sparse or upload analysis, only `latest` is supported.) 

This endpoint reports a summary of results for each language, and also the analysis identifier. You can use the analysis identifier to download full details of all the alerts  found by the analysis. For more information, see [Get detailed alert information](https://lgtm.com/help/lgtm/api/api-v1#opIdgetAlerts).
 """,
    tags=['code_analysis', 'version_info'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_analysis_for_commit(
    project_id: int = Path(..., alias='project-id'),
    commit_id: str = Path(..., alias='commit-id'),
):
    """
    Get analysis summary for a specific commit
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/codereviews/{project-id}',
    description=""" Trigger the code review of a patch. This is available for projects with Git repositories.

Your request must include:

  * Identifier for the base commit
  * Patch generated using `git diff --binary` (see [git diff](https://git-scm.com/docs/git-diff))
  * Header `Content-Type: application/octet-stream`
  * For both LGTM.com and LGTM Enterprise, an access token with the `codereviews:write` scope

Note that if you make a request using Curl, you'll also need to add `--data-binary` to the request to ensure that the patch you supply in the body is sent with newlines unchanged.
You can track the progress of the review using the task result URL returned on creation of the task, or by calling the `/operations` endpoint with the operations identifier returned by the request. For more information, see [Get operation status](https://lgtm.com/help/lgtm/api/api-v1#opIdgetOperation). Alternatively, if you supply a callback URL you'll get a post-back automatically on completion of the review.

When the review is complete, you can access the results using the task result URL.
 """,
    tags=['code_analysis', 'code_review_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def request_review(
    project_id: int = Path(..., alias='project-id'),
    base: str = ...,
    external_id: int = Query(..., alias='external-id'),
    review_url: Optional[str] = Query(None, alias='review-url'),
    callback_url: Optional[str] = Query(None, alias='callback-url'),
    callback_secret: Optional[str] = Query(None, alias='callback-secret'),
    request: Request = ...,
):
    """
    Run code review for a patch
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/codereviews/{review-id}',
    description=""" Get the results of a code review using the review identifier for the task.

When you request a code review, the response includes a task result URL of the form: `/codereviews/{review-id}`.

This endpoint reports the results of a complete code review, or the status of a review  that's still in progress.
 """,
    tags=['code_review_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_code_review(review_id: str = Path(..., alias='review-id')):
    """
    Get results of code review
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/issues/{project-id}/{alert-key}',
    description=""" Fetch the alert information for an issue in [SARIF](https://lgtm.com/help/lgtm/sarif-results-file) format.
 """,
    tags=['project_configuration', 'query_execution_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_issue(
    project_id: int = Path(..., alias='project-id'),
    alert_key: str = Path(..., alias='alert-key'),
):
    """
    Get detailed alert information for an issue
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/openapi',
    description=""" Get the specification of this API in [OpenAPI](https://github.com/OAI/OpenAPI-Specification) format. This endpoint does not require an access token. This makes it easier for you to use the specification with third-party tools. """,
    tags=['version_info'],
)
def get_spec():
    """
    API specification
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/operations/{operation-id}',
    description=""" Track progress of a long-running operation using the operations identifier returned when you  created the operation. For example, by triggering the analysis of a commit, or the code review of a patch. For both LGTM.com and LGTM Enterprise, you must include an access token with the `operations:read` scope.
 """,
    tags=['application_health_metrics'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_operation(operation_id: int = Path(..., alias='operation-id')):
    """
    Get operation status
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/projects',
    description=""" List all the projects the current user has authorization to view. 

A maximum of 100 projects are returned in each response. When further results are available, the response includes the URL you need to request the next page of results.

Use the optional parameter, `limit`, to change the number of results reported in each response (range of 1&mdash;100). If you supply an invalid value for this  parameter, the default value of 100 is used.

When more than one page of results is available, each response includes a `nextPageUrl` response parameter. You can use this URL to request the next page of results. The `nextPageUrl` includes an automatically generated `start` parameter, which specifies the projects to return in the next page of results.
 """,
    tags=['project_configuration'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_projects(
    limit: Optional[conint(ge=1, le=100)] = 100, start: Optional[str] = None
):
    """
    List projects
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/projects',
    description=""" LGTM administrators can add a new project to LGTM by providing a repository URL. By default, LGTM tries to build and analyze the project in the same way as for projects added through the user interface. If at least one language is successfully analyzed, and the repository doesn't already exist on LGTM, a new project is created. If the project already exists but your API call triggers a successful analysis  of additional languages, LGTM adds those languages to the project.

You can configure how LGTM processes the project using query parameters to:
  * Specify the languages to analyze.
  * Create a new project in [sparse mode](https://help.semmle.com/lgtm-enterprise/user/help/analysis-faqs.html#what-is-sparse-analysis).
  * Create a new project in [upload mode](https://help.semmle.com/lgtm-enterprise/user/help/analysis-faqs.html#what-is-upload-analysis) to analyze externally-generated databases. Each database represents a snapshot of the codebase. 
  Use this option when you want to upload databases that were generated by the CodeQL CLI (or the QL command-line tools).
  The version of the command line used to generate the database
  must be the same version as LGTM Enterprise. 

With any of these options, you can also include an `lgtm.yml` in the body of the request to [customize extraction](https://lgtm.com/help/lgtm/customizing-code-extraction).
 """,
    tags=['project_configuration'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def add_project(
    repository: AnyUrl,
    language: Optional[Language1] = None,
    mode: Optional[Mode] = None,
    commit: Optional[str] = None,
    date: Optional[datetime] = None,
    worker_label: Optional[WorkerLabel] = Query(None, alias='worker-label'),
):
    """
    Add a project to LGTM
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/projects/{project-id}',
    description=""" Delete a project with a particular numeric project identifier.
In addition to access to the project, administrative access to LGTM or the LGTM Enterprise instance is required to delete projects.
 """,
    tags=['project_configuration'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def delete_project(project_id: conint(ge=1) = Path(..., alias='project-id')):
    """
    Delete project by numeric identifier
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/projects/{project-id}',
    description=""" Get the latest summary for a specific project using the numeric project identifier.

To find the LGTM identifier for a project, list all projects using the `/projects`  endpoint and look up the project by name. Alternatively, use the `/projects/{provider}/{org}/{name}` endpoint. If you have administration access, the project identifier is also displayed in  the administration page for the project.
 """,
    tags=['project_configuration'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_project(project_id: conint(ge=1) = Path(..., alias='project-id')):
    """
    Get project by numeric identifier
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/projects/{project-id}/settings/analysis-configuration',
    description=""" Get the latest configuration for a specific project using the numeric project identifier. """,
    tags=['project_configuration'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_project_config(
    project_id: int = Path(..., alias='project-id'), source: Optional[Source] = None
):
    """
    Get configuration for a project identified by numeric identifier
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/projects/{project-id}/settings/analysis-configuration',
    description=""" Set the administrator configuration for a specific project using the numeric project identifier. """,
    tags=['project_configuration'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def set_project_config(project_id: int = Path(..., alias='project-id')):
    """
    Set the administrator configuration for a project identified by numeric identifier
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/projects/{provider}/{org}/{name}',
    description=""" Get the latest summary for a specific project using the project's URL identifier `{provider}/{org}/{name}`.

To find the URL identifier for a project, view the project overview page in LGTM. The URL identifier follows after `/projects`. For example, for a project with the URL `https://lgtm.example.com/projects/g/apache/commons-io` the URL identifier is `g/apache/commons-io`. In the example, `g` represents the `provider` (repository host), `apache` is the `organization` and `commons-io` is the `name` of the repository.
 """,
    tags=['project_configuration'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_project_by_url_identifier(provider: str, org: str = ..., name: str = ...):
    """
    Get project by URL identifier
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/queryjobs',
    description=""" Submit a query to run on one or more projects on LGTM. The query is included in the body of the request.
 """,
    tags=['code_analysis', 'query_execution_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def create_query_job(
    language: str,
    project_id: Optional[ProjectId] = Query(None, alias='project-id'),
    projects_list: Optional[str] = Query(None, alias='projects-list'),
):
    """
    Run a CodeQL query on one or more projects
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/queryjobs/{queryjob-id}',
    description=""" Get the status of a query job using the query job identifier for the task.

When you create a query job, the response includes a task result URL of the form: `/queryjobs/{queryjob-id}`.
 """,
    tags=['query_execution_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_query_job(queryjob_id: str = Path(..., alias='queryjob-id')):
    """
    Get the status of a query job
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/queryjobs/{queryjob-id}/results',
    description=""" This endpoint provides a summary of the results generated by completed query runs for each  project specified in the the POST /queryjobs endpoint.  For completed query jobs, the summary includes:

  * The number of results for successful query runs.
  * Error information for failed query runs.

No information is included in the response for any project for which the query  run is still in progress.
 """,
    tags=['query_execution_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_query_job_results_overview(
    queryjob_id: str = Path(..., alias='queryjob-id'),
    start: Optional[str] = None,
    limit: Optional[int] = 100,
    filter: Optional[str] = None,
):
    """
    Provide a summary of results for the projects in the query job
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/queryjobs/{queryjob-id}/results/{project-id}',
    description=""" Fetch the results for a specific project. The endpoint succeeds only if the query was successful,  and returns a `404` error otherwise.  By default, the endpoint provides only results that are within the source tree. To obtain all results, specify the `nofilter` parameter.
 """,
    tags=['query_execution_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_query_job_results_for_project(
    queryjob_id: str = Path(..., alias='queryjob-id'),
    project_id: str = Path(..., alias='project-id'),
    start: Optional[int] = None,
    limit: Optional[int] = 100,
    nofilter: Optional[bool] = False,
):
    """
    Fetch the results of a query job for a specific project
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/snapshots/uploads/{session-id}',
    description=""" Aborts the specified upload session and deletes any uploaded parts. After the session is aborted it cannot be restarted.
If any part uploads are in progress when the session is aborted, their data may not be deleted. To ensure that uploaded parts are deleted correctly, you should only abort an upload session after all part uploads have completed.
 """,
    tags=['snapshot_upload_control'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def abort_upload(session_id: str = Path(..., alias='session-id')):
    """
    Abort database upload process
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/snapshots/uploads/{session-id}',
    description=""" Completes the database upload by closing the upload session, upgrading the database if appropriate, and scheduling analysis of that snapshot of the codebase.

You can view the analysis progress and access the results using the `task-result-url`.
 """,
    tags=['snapshot_upload_control'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def complete_upload(session_id: str = Path(..., alias='session-id')):
    """
    Complete snapshot upload session
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/snapshots/uploads/{session-id}',
    description=""" Upload a database representing a snapshot of a codebase.  The database is sent in one or more parts. Each part is sent in the request body. 
Use the [`POST /snapshots/{project-id}/{language}`](https://lgtm.com/help/lgtm/api/api-v1#opIdinitSnapshotUpload) endpoint  to start an upload session before uploading a database part. Database parts must have been generated and prepared for upload using the CodeQL CLI or the QL command-line tools. For further information on exporting externally-built databases,  see [Preparing snapshots to upload to LGTM](https://help.semmle.com/wiki/display/SD/Preparing+snapshots+to+upload+to+LGTM).

Split large databases into multiple parts. Upload the parts by making a separate request for each part.  Don't upload the next part until you've successfully uploaded the previous part.

If the upload fails you should retry it with the same data.
 """,
    tags=['snapshot_upload_control'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def upload_part(
    session_id: str = Path(..., alias='session-id'), request: Request = ...
):
    """
    Upload snapshot
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/snapshots/{project-id}/{language}',
    description=""" Download a CodeQL database from LGTM, representing a snapshot of the codebase, to run queries in your IDE.

This endpoint works for projects that have been successfully analyzed for the language specified in the request.  A successful request redirects you to a URL for downloading a database that represents the code snapshot, as specified in the `Location:` header in the response. Therefore, your HTTP client should be configured to follow redirects. For example, if you are using `curl`, you can add the`-L` flag to the command.

The database is downloaded as a zip file that can be imported into an IDE equipped with a  CodeQL extension. The extension must be up to date to analyze databases downloaded from LGTM. For more information on running queries locally in your IDE, see [Runnning queries in your IDE](https://lgtm.com/help/lgtm/running-queries-ide). 
 """,
    tags=['snapshot_upload_control'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_snapshot(project_id: int = Path(..., alias='project-id'), language: str = ...):
    """
    Download a snapshot
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/snapshots/{project-id}/{language}',
    description=""" Start a session to upload an externally-built database (which represents a snapshot of a codebase) to a project on LGTM. 

This endpoint works for projects that are already on LGTM, and the selected language of  the database must already be configured. The project must be configured with 'upload' analysis mode. You can upload a "bundled" CodeQL database or a database exported by  the QL command-line tools (`odasa`).

If your database was generated using a version of the  command line that is older than LGTM,  LGTM will try to upgrade and analyze it when the upload is complete. You can include cached predicates in the upload, but they are ignored as the cache is  repopulated after the database has been upgraded and analyzed. However, if you want to include results with your database, make sure the database is  compatible before you start the upload session.  Incompatible databases with results won't be upgraded and therefore cannot be uploaded.  For further information on externally-built databases,  see [Preparing snapshots to upload to LGTM using the QL command-line tools](https://help.semmle.com/wiki/display/SD/Preparing+snapshots+to+upload+to+LGTM).

    
When the upload session has been successfully started, upload the database to the  upload URL returned in the response. The database can be uploaded to the upload URL in parts using  the [`PUT /snapshots/uploads/{session-id}`](https://lgtm.com/help/lgtm/api/api-v1#opIduploadPart) endpoint. After uploading all the parts you must call  the [`POST /snapshots/uploads/{session-id}`](https://lgtm.com/help/lgtm/api/api-v1#opIdcompleteUpload) endpoint to complete the upload session.
 """,
    tags=['snapshot_upload_control'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def init_snapshot_upload(
    project_id: int = Path(..., alias='project-id'),
    language: str = ...,
    commit: str = ...,
    date: Optional[datetime] = None,
):
    """
    Start snapshot upload session
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/system/health',
    description=""" Return an indication of whether the application is working as expected (up) or needs  attention (down). 
\> The `description` and `details` fields are reported only if the request includes an access token for a user account that has administration rights for this LGTM server.
 """,
    tags=['application_health_metrics'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_health():
    """
    Get a summary of the application's health
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/system/metrics',
    description=""" LGTM administrators can use this endpoint to list the usage metrics that are available to download.
 """,
    tags=['application_health_metrics'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_metrics():
    """
    Get the identifiers and descriptions of the usage metrics
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/system/metrics/{metric-id}',
    description=""" LGTM administrators can download usage data using this endpoint. The response includes up to 1000 values for the specified metric and reports the date-time that each value was calculated. There is normally one value per day.
 """,
    tags=['application_health_metrics'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_metric(metric_id: str = Path(..., alias='metric-id')):
    """
    Get the computed values of the specified metric
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
